cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns=[
    path('',views.detail,name='detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>',views.remove_cart,name='remove_cart'),
]

onlineStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('',include('shop.urls',namespace='shop'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
app_name='orders'
urlpatterns=[
    path('create/',views.create_order,name='create_order'),
    path('<int:id>/',views.detail,name='detail'),
    path('payment/<int:id>/<int:price>/',views.payment,name='payment'),
    path('verify/',views.verify,name='verify'),
    path('apply/<int:order_id>/',views.apply_coupon ,name='apply_coupon'),
    ]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity=forms.IntegerField(max_value=9,min_value=1)

cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .cart import Cart
from shop.models import Product
from .forms import CartAddForm
from django.views.decorators.http import require_POST

# Create your views here.
def detail(request):
    cart=Cart(request)
    return render(request ,'cart/detail.html',{'cart':cart})


@require_POST
def cart_add(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=product_id)
    form=CartAddForm(request.POST)
    if form.is_valid():
        cd=form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'])
    return redirect('cart:detail')


def remove_cart(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">product</th>
      <th scope="col">quantity</th>
      <th scope="col">unit price</th>
      <th scope="col">total price</th>
      <th scope="col">remove</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.product}}</td>
      <td>{{ item.quantity }}</td>
      <td>{{ item.price }}</td>
      <td>{{ item.total_price }}</td>
      <td><a href="{%  url 'cart:remove_cart' item.product.id %}">remove</a></td>
    </tr>
  {% endfor %}
  <tr>
      <td></td>
      <td colspan="4">total </td>
      <td>{{ cart.get_total_price }}</td>
  </tr>
  </tbody>
</table>
    <a href="{% url 'orders:create_order' %}" class="btn btn-primary">checkout</a>
{% endblock %}