cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns=[
    path('',views.detail,name='detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>',views.remove_cart,name='remove_cart'),
]

onlineStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('',include('shop.urls',namespace='shop'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns=[
    path('',views.home,name='home'),
    path('<slug:slug>/',views.detail_product,name='detail'),
    path('category/<slug:slug>',views.home ,name='category')
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    sub_category=models.ForeignKey('self',on_delete=models.CASCADE,related_name='scategory',null=True,blank=True)
    is_sub=models.BooleanField(default=False)
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200,unique=True)


    class Meta:
        ordering=('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category',args=[self.slug,])


class Product(models.Model):
    category=models.ManyToManyField(Category , related_name='cproduct')
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200, unique=True)
    image=models.ImageField(upload_to='product/%Y/%m/%d/')
    description=models.TextField()
    price=models.IntegerField()
    availble=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail',args=[self.slug,])

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddForm

# Create your views here.

def home(request,slug=None):
    products=Product.objects.filter(availble=True)
    categorys =Category.objects.filter(is_sub=False)
    if slug:
        category=get_object_or_404(Category,slug=slug)
        products=products.filter(category=category)
    return render(request,'shop/home.html',{'products':products,'categorys':categorys})


def detail_product(request,slug):
    products=get_object_or_404(Product,slug=slug)
    form=CartAddForm()
    return render(request,'shop/detail_product.html',{'product':products,'form':form})

shop/templates/shop/detail_product.html
{% extends 'base.html' %}

{% block content %}
<H3>{{ product.name }}</H3>
    <small>{{ product.created }}</small><p>{{ product.price }} $</p><br>
    <img src="{{ product.image.url }}" height="200px" width="200px"> <br><br><br>
    <p>{{ product.description }}</p><br><br>
    <form method="post" action="{% url 'cart:cart_add' product.id %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="add to cart" class="btn btn-danger">
    </form>
{% endblock %}

shop/templates/shop/home.html
{% extends 'base.html' %}

{% block content %}
{% load thumbnail %}
    <h3>home</h3>
    {% for category in categorys %}
            <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" type="button" class="btn btn-primary">{{ category.name }}</a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                {%  for sub in category.scategory.all %}
                    <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
                {% endfor %}
            </div>
            </div>
    {% endfor %}<br><br><br>
    {% for product in products %}
        <div class="card" style="width: 18rem; display: inline-block">
        {%  thumbnail product.image "200x200" as img %}
        <img src="{{ img.url }}" class="card-img-top" alt="..." width="200" height="200">
        {% endthumbnail %}
            <div class="card-body">
            <h5 class="card-title">{{ product.name}}</h5>
            <a href="{{ product.get_absolute_url }}" class="btn btn-primary">go to product page</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}