accounts/urls.py
from . import views
from django.urls import path

app_name='accounts'
urlpatterns=[
    path('login/',views.login_user  , name='login'),
    path('logout/',views.logout_user , name='logout'),
    path('signup/',views.sign_up , name='signup'),
]

cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns=[
    path('',views.detail,name='detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>',views.remove_cart,name='remove_cart'),
]

onlineStore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('',include('shop.urls',namespace='shop'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns=[
    path('',views.home,name='home'),
    path('<slug:slug>/',views.detail_product,name='detail'),
    path('category/<slug:slug>',views.home ,name='category')
]

templates/inc/message.html
{% if messages %}
{% for msg in messages %}
    <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
{% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="nav-link" href="{% url 'shop:home' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
    {% else %}
        <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
        <a class="nav-link" href="{% url 'accounts:signup' %}">signup</a>
    {% endif %}
</nav>